**Deklarasi Matriks**
1. Deklarasi sekaligus inisialisasi nilai matriks.  
Cara pertama adalah mendeklarasikan matriks sekaligus menginisialisasikan nilainya dengan ukuran N baris dan M Kolom (NxM). Cara ini dilakukan jika kita telah mengetahui nilai yang perlu diberikan.
```
< nama—var> = [[ val-11, val-12, ... val-1m],
                [val-21, val-22,... val-2m],
                ......
                [val-n1, val, n2, ... val-nm]]
```

In [ ]:
Gambar di atas merupakan struktur jika kita ingin mendeklarasikan matriks dengan ukuran nxm.  


In [ ]:
import numpy
matriks = numpy.array([[1, 0, 0, 0, 0],
            [0, 1, 0, 0, 0],
            [0, 0, 1, 0, 0],
            [0, 0, 0, 1, 0],
            [0, 0, 0, 0, 1]])
     
print(matriks)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Pada kode di atas, kita mendeklarasikan variabel matriks dan menginisialisasikannya dengan matriks satuan dan memiliki ukuran baris = 5 dan ukuran kolom = 5. Matriks satuan adalah jenis matriks dengan elemen bernilai hanya 0 dan 1.

2. **Deklarasi dengan nilai default.**
Cara kedua adalah mendeklarasikan matriks dengan nilai default.  

nilai default ditentukan oleh kesepakatan bersama sesuai kebutuhan dengan nilainya di luar rentang yang ditentukan. Misalnya, tim Anda menentukan nilai dalam list harus berkisar dari 1 hingga 10. Kita bisa menyepakati nilai "0" sebagai nilai default karena di luar jangkauan yang disepakati (1-10). Cara kedua ini melibatkan list comprehension yang sama seperti pada materi array.
`<nama—var> = [[<default-val> for j in range (<m>)] for i in range (<n>)]`  
Terlihat pada struktur tersebut, cara kedua ini menggunakan dua metode sekaligus, yakni nested list dan nested for.  
Nilai dari `<default-val>` ditentukan kesepakatan bersama, misalnya jika range yang disepakati adalah 1 hingga 10, kita bisa memilih 0 untuk nilai default-nya. Ada pula `<n>` sebagai jumlah baris matriks yang ingin dibuat dan `<m>` sebagai jumlah kolom matriks yang diinginkan.


In [ ]:
matrix = numpy.array([[0 for j in range (5)] for i in range(5)])
print(matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Pada kode di atas, kita mendeklarasikan variabel matriks dan menginisialisasikannya dengan nested list dan nested for serta nilai default-nya adalah 0. Matriks yang dibuat pada program di atas adalah matriks value dengan setiap elemennya bertipe integer serta memiliki ukuran baris = 5 dan ukuran kolom = 4.

**Akses Elemen Matriks**
jika Anda ingin mengakses elemen dari matriks, perlu mengetahui indeks dari baris dan kolom.  
Kita akan mengakses elemen matriks menggunakan metode indexing. Ini artinya Anda perlu mengetahui indeks dari baris dan kolom yang ingin diakses.
`<namamatriks> [<nbrs>][<nkol >]`  
`<nbrs>` merupakan nomor indeks baris yang ingin diakses, dan `<nkol>` nomor indeks kolom yang ingin diakses.

In [16]:
var_mat = numpy.array([[1, 2, 3, 4, 5],
           [6, 7, 8, 9, 10],
           [11, 12, 13, 14, 15],
           [16, 17, 18, 19, 20],
           [21, 22, 23, 24, 25]])
print(var_mat[4][2])

23
